version: "2"

services:
  mongodb-primary:
    image: "docker.io/bitnami/mongodb:4.4-debian-10"
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    volumes:
      - "mongodb_master_data:/bitnami/mongodb"
    ports:
      - 27017:27017

  mongodb-secondary:
    image: "docker.io/bitnami/mongodb:4.4-debian-10"
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123

  mongodb-arbiter:
    image: "docker.io/bitnami/mongodb:4.4-debian-10"
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-arbiter
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123

  api:
    image: datapad-data-api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongodb-primary
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://root:password123@mongodb-primary,mongodb-secondary,mongodb-arbiter/dh_pim?authSource=admin

volumes:
  mongodb_master_data:
    driver: local
